neo4jproject/Book/urls.py
from django.conf.urls import url, include 
from django.contrib import admin 
from django.views.generic import TemplateView
from django.urls import path
from Book import views

app_name ='Book'
urlpatterns = [
    path('index',views.index),
    path('',views.Mylogin,name ='login'),
    path('logout',views.Mylogout, name='logout'),
    path('register',views.MyRegister, name = 'register'),
]

neo4jproject/neo4jproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Book.urls')),
]

neo4jproject/Book/models.py
from django.db import models
from neomodel import StructuredNode,StringProperty, UniqueIdProperty, DateProperty, EmailProperty, RelationshipTo
from django_neomodel import DjangoNode 

class Book(DjangoNode):
    ID = UniqueIdProperty()
    code = StringProperty(unique_index=True, required=True, primary_key=True)
    name = StringProperty(index=True)
    class Meta:
        app_label = 'Book'

class User(DjangoNode):
    ID = UniqueIdProperty()
    fullname =StringProperty()
    username = StringProperty()
    password = StringProperty()
    email = EmailProperty(unique_index = True)

    # Relations :
    book = RelationshipTo('Book', 'pushlish')
    class Meta:
        app_label = 'Book'

neo4jproject/Book/views.py
from os import name
from django.shortcuts import redirect, render
from .models import Book, User
from django.contrib.auth import logout
# Create your views here.

def index(request):
    if request.method == 'POST':
        user = User.nodes.get_or_none(username = search)
        if user == None:
            return render(request,'Book/index.html',{'message':'tác giả bạn tìm không tồn tại'})
        else:
            books = user.pushlish.all()
            print(books)
            for book in books:
                print(book.name)
            return render(request,'Book/index.html',{'books':books})
    return render(request,'Book/index.html')

def Mylogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.nodes.get_or_none(username=username)
        
        if user == None:
            return render(request,'Book/login.html',{'message':'Tài khoản của bạn không tồn tại'})
        else:
            if user.password == password:
                return render(request,'Book/index.html',{'message':user.fullname})
            else:
                 return render(request,'Book/login.html',{'message':'mật khẩu của bạn không đúng'})
    return render(request,'Book/login.html')

def Mylogout(request):
    try:
        logout(request)
    except:
        pass
    return redirect('Book:login')

def MyRegister(request):
    if request.method == 'POST':
        fullname = request.POST.get('fullname')
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        print(password2,password)
        user = User.nodes.get_or_none(username=username)
        if user == None:
            if password == password2:
                new_user = User(username = username,password =password, fullname = fullname)
                new_user.save()
                return redirect('Book:login')
            else:
                return render(request,'Book/register.html',{'message':'mật khấu xác nhận bạn không đúng'})
        else:
            return render(request,'Book/register.html',{'message':'tài khoản đã tồn tại'})
    return render(request,'Book/register.html')

neo4jproject/Book/templates/Book/index.html
<html>
<title>Tran's book</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Tahoma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>

<div class="w3-top">
{% load static %}
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a href="#home" class="w3-bar-item w3-button">TIỆM SÁCH CỦA BẢO TRÂN</a>
    <!-- Right-sided navbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#" class="w3-bar-item w3-button">Trang chủ</a>
      <a href="{% url 'Book:register' %}" class="w3-bar-item w3-button">Đăng ký</a>
      <a href="#contact" class="w3-bar-item w3-button">Thêm sách</a>
    </div>
   <form class="navbar-form navbar-left" role="search" method="POST" action="">
    {% csrf_token %}          
                    <div class="form-group">
                        <input type="text" class="form-control" name="check" type="text">
                    </div>
                    <button type="submit" class="btn btn-default">Tìm kiếm</button>
    </form>
  </div>
    
</div>
 
<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

  <!-- First Photo Grid-->
   <h4>Sách mới nhất </h4>
    {% if message %} {{message}} {% endif %} {% for showbook in books %}
    
        <div class="w3-row-padding w3-padding-16 w3-center" id="food">
            <div class="w3-quarter">
            <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
            <h3>{{showbook.name}}</h3>
            </div>
        </div>
      {% endfor %}   
   
</html>  
  

neo4jproject/Book/templates/Book/login.html
<html>
<title>Tran's Book</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-padding-15" id="contact">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Đăng nhập tài khoản</h3>
     {% if message %} {{message}} {% endif %}
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
    <p> Bạn chưa có tài khoản? <a href="{% url 'Book:register' %}">Chọn vào đây</a> để đăng kí.</p>
    <form action="/action_page.php" target="_blank">
      <input class="w3-input w3-border" type="text" id="id_username" placeholder="Tài khoản" name="username">
      <input class="w3-input w3-section w3-border" id="id_password" type="password" placeholder="Mật khẩu" required name="password">
      
      <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Xác nhận</button>
                                </div>
                            </div>
    </form>
  </div>
</html>  

neo4jproject/Book/templates/Book/register.html
<html>
<title>Tran's Book</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-padding-32" id="contact">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Đăng ký tài khoản</h3>
    <p> Hãy điền đầy đủ thông tin nhé!</p>
     {% if message %} {{message}} {% endif %}
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
    <form action="/action_page.php" target="_blank">
      
      <input class="w3-input w3-section w3-border" type="text" placeholder="Họ và tên" name="fullname">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Email"  name="Email">
      <input class="w3-input w3-border" type="text" id="id_username"  placeholder="Tên tài khoản"  name="username">
      <input class="w3-input w3-section w3-border" id="id_password" type="password" placeholder="Mật khẩu" required name="password">
      <input class="w3-input w3-section w3-border" id="id_password" type="password" placeholder="Nhập lại mật khẩu" required name="password2">
      <button class="w3-button w3-black w3-section" type="submit"> 
        <i class="fa fa-paper-plane" ></i> ĐĂNG KÝ 
      </button>
       <button class="w3-button w3-black w3-section" type="submit">
        <i class="fa fa-paper-plane"></i>  QUAY VỀ
      </button>
    </form>
  </div>
</html>  